export HomePage from './HomePage';
export ProductPageLazy from './ProductPage';
export Header from './Header';
export SignIn from './SignIn';
export Login from './Login';
export ContactForm from './Form';
export Layer from './Layer';
export Registration from './Registration';
// export UserNavbar from './UserNavbar';
export Dashboard from './Dashboard';
// export ShoppingCart from './ShoppingCart';
export ShoppingCartLazy from './ShoppingCartLazy';
export Filters from './Filters';
export OrderLazy from './Order';
export ContactPhone from './ContactPhone';
export CountDownDate from './CountDownDate';
export GeneralBanner from './GeneralBanner';
export RotatingBlock from './RotatingBlock';
export Footer from './Footer';
export Review from './Review';
export StarsAndTotalReviews from './StarsAndTotalReviews';
export Notifier from './Notifier';
export Preloader from './Preloader';
export RepairLazy from './Repair';
export Sorting from './Filters/components/Sorting/Sorting';
// export Product from './Products/Product';