export HomePage from './HomePage';
export ProductPage from './ProductPage';
export Header from './Header';
export SignIn from './SignIn';
export Login from './Login';
export ContactForm from './Form';
export Layer from './Layer';
export Registration from './Registration';
// export UserNavbar from './UserNavbar';
export Dashboard from './Dashboard';
export ShoppingCart from './ShoppingCart';
export ShoppingCartLazy from './ShoppingCartLazy';
export Filters from './Filters';
export Order from './Order';
export ContactPhone from './ContactPhone';
export CountDownDate from './CountDownDate';
export GeneralBanner from './GeneralBanner';
export RotatingBlock from './RotatingBlock';